array_width = 80
attr_fn_like_width = 80
# brace_style = "PreferSameLine"
chain_width = 80
# comment_width = 100
# empty_item_single_line = true
fn_args_layout = "Compressed"
fn_call_width = 80
# fn_single_line = true
# force_multiline_blocks = true
# format_code_in_doc_comments = true
# indent_style = "Visual"
match_block_trailing_comma = true
max_width = 120
# imports_granularity = "Crate"
# reorder_impl_items = true
reorder_imports = true
# group_imports = "StdExternalCrate"
single_line_if_else_max_width = 60
# space_after_colon = true
# space_before_colon = false
# space_around_ranges = false
# struct_field_align_threshold = 0
# struct_lit_single_line = true
struct_lit_width = 40
struct_variant_width = 40
# trailing_comma = "Never"
use_field_init_shorthand = true
# where_single_line = true
# wrap_comments = true



